import type { Config } from "tailwindcss";
// const colsAmount = ['4', '6', '8', '10', '12', '16'];
const fontSizes = ["xs", "sm", "md", "lg", "xl", "2xl"];
const fontWeight = ["regular", "medium", "semibold", "bold", "black"];
const bgColors = [
  "primary",
  "secondary",
  "inverse",
  "accent",
  "highlight",
  "muted",
  "background",
  "foreground",
  "green",
];
// const safeCols = colsAmount.flatMap((amount) => [`grid-cols-${amount}`]);
const safeFontSizes = fontSizes.flatMap((size) => [`font-${size}`]);
const safeFontWeights = fontWeight.flatMap((weight) => [`font-${weight}`]);
const safeBgColors = bgColors.flatMap((color) => [`bg-${color}`]);

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    // ...safeCols,
    ...safeFontWeights,
    ...safeFontSizes,
    ...safeBgColors,
    "mix-blend-difference",
  ],
  theme: {
    extend: {
      screens: {
        ipad: {
          raw: "(min-width: 768px) and (max-width: 1279px) and (min-height: 1024px)",
        },
      },
      colors: {
        primary: "var(--primary)",
        secondary: "var(--secondary)",
        inverse: "var(--inverse)",
        accent: "var(--accent)",
        highlight: "var(--highlight)",
        muted: "var(--muted)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        alert: "var(--alert)",
        green: "var(--green)",
        gold: "var(--gold)",
        violet: "var(--violet)",
        "violet-50": "var(--violet-50)",
      },
      width: {
        "screen-1/4": "var(--w-25)",
        "screen-2/4": "var(--w-50)",
        "screen-3/4": "var(--w-75)",
        "screen-4/4": "var(--w-100)",
        "screen-1/3": "var(--w-33)",
        "screen-2/3": "var(--w-66)",
        "screen-5/6": "83.33vw",
      },
      minWidth: {
        "screen-1/4": "var(--w-25)",
        "screen-2/4": "var(--w-50)",
        "screen-3/4": "var(--w-75)",
        "screen-4/4": "var(--w-100)",
        "screen-1/3": "var(--w-33)",
        "screen-2/3": "var(--w-66)",
        "screen-5/6": "83.33vw",
      },
      height: {
        "screen-1/4": "var(--h-25)",
        "screen-2/4": "var(--h-50)",
        "screen-3/4": "var(--h-75)",
        "screen-4/4": "var(--h-100)",
      },
      minHeight: {
        "screen-1/4": "var(--h-25)",
        "screen-2/4": "var(--h-50)",
        "screen-3/4": "var(--h-75)",
        "screen-4/4": "var(--h-100)",
      },
      fontFamily: {
        sans: "var(--sans)",
        serif: "var(--serif)",
      },
      fontSize: {
        xxs: "var(--text-xxs)",
        xs: "var(--text-xs)",
        sm: "var(--text-sm)",
        md: "var(--text-md)",
        lg: "var(--text-lg)",
        xl: "var(--text-xl)",
        "2xl": "var(--text-2xl)",
        "3xl": "var(--text-3xl)",
        "4xl": "var(--text-4xl)",
        "vw-xs": "var(--text-vw-xs)",
        "vw-sm": "var(--text-vw-sm)",
        "vw-md": "var(--text-vw-md)",
        "vw-lg": "var(--text-vw-lg)",
        "vw-xl": "var(--text-vw-xl)",
        title: "var(--text-title)",
        "title-sm": "var(--text-title-sm)",
        "title-md": "var(--text-title-md)",
        "title-xl": "var(--text-title-xl)",
        hero: "var(--text-hero)",
        "hero-lg": "var(--text-hero-lg)",
        "about-xs": "26.2vw",
        "about-sm": "26.8vw",
        "about-md": "26.7vw",
        "about-lg": "27.2vw",
        "about-xl": "clamp(54px, 27.8vw, 354px)",
      },
      fontWeight: {
        bold: "700",
        extrabold: "800",
      },
      padding: {
        xxs: "var(--p-xxs)",
        xs: "var(--p-xs)",
        sm: "var(--p-sm)",
        md: "var(--p-md)",
        lg: "var(--p-lg)",
        xl: "var(--p-xl)",
        "2xl": "var(--p-2xl)",
        "3xl": "var(--p-3xl)",
        "4xl": "var(--p-4xl)",
        "5xl": "var(--p-5xl)",
      },
      margin: {
        xs: "var(--m-xs)",
        sm: "var(--m-sm)",
        md: "var(--m-md)",
        lg: "var(--m-lg)",
        xl: "var(--m-xl)",
        "2xl": "var(--m-2xl)",
        "3xl": "var(--m-3xl)",
        "4xl": "var(--m-4xl)",
        "5xl": "var(--m-5xl)",
      },
      gap: {
        xxs: "var(--gap-xxs)",
        xs: "var(--gap-xs)",
        sm: "var(--gap-sm)",
        md: "var(--gap-md)",
        lg: "var(--gap-lg)",
        xl: "var(--gap-xl)",
        "2xl": "var(--gap-2xl)",
        "3xl": "var(--gap-3xl)",
        "4xl": "var(--gap-4xl)",
      },
      transitionProperty: {
        fading: "opacity, transform",
      },
      transitionTimingFunction: {
        ease: "var(--ease)",
        in_out: "var(--ease_in_out)",
        _in_out_q: "var(----ease_in_out-q)",
        out: "var(----ease_out)",
      },
      keyframes: {
        "swipe-in-left": {
          "0%": { opacity: "0", transform: "translateX(-40px) scale(.98)" },
          "100%": { opacity: "1", transform: "translateX(0) scale(1)" },
        },
        "swipe-in-right": {
          "0%": { opacity: "0", transform: "translateX(40px) scale(.98)" },
          "100%": { opacity: "1", transform: "translateX(0) scale(1)" },
        },
        "swipe-out-left": {
          "0%": { opacity: "1", transform: "translateX(0) scale(1)" },
          "100%": { opacity: "0", transform: "translateX(-40px) scale(.98)" },
        },
        "swipe-out-right": {
          "0%": { opacity: "1", transform: "translateX(0) scale(1)" },
          "100%": { opacity: "0", transform: "translateX(40px) scale(.98)" },
        },
        "counter--to-top": {
          "0%": { transform: "translateY(0)" },
          "40%": { transform: "translateY(-8px)", opacity: "0" },
          "51%": { transform: "translateY(8px)", opacity: "0" },
          "90%": { transform: "translateY(0)", opacity: "1" },
        },
        "counter--to-bottom": {
          "0%": { transform: "translateY(0)" },
          "40%": { transform: "translateY(8px)", opacity: "0" },
          "51%": { transform: "translateY(-8px)", opacity: "0" },
          "90%": { transform: "translateY(0)", opacity: "1" },
        },
        squize: {
          "0%": { transform: "scale(1,1) translateY(0)" },
          "40%": { transform: "scale(1.2,0.8) translateY(3px)" },
          "100%": { transform: "scale(1,1) translateY(0)" },
        },
        "bounce--down": {
          "0%": { transform: "translateX(0)" },
          "12%": { transform: "translateX(4px) scaleY(0.9)" },
          "40%": { transform: "translateX(5px) scaleY(0.85)" },
          "66%": { transform: "translateX(-2px)" },
          "80%": { transform: "translateX(0) scaleY(1)" },
        },
        parallax: {
          from: { backgroundPosition: "bottom 25% center" },
          to: { backgroundPosition: "top 0 center" },
        },
        "parallax-xl": {
          from: { backgroundPosition: "top 33% center" },
          to: { backgroundPosition: "top 12vh center" },
        },
        rotate: {
          "0%": { transform: "rotate(0deg)" },
          "50%": { transform: "rotate(180deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
      },
      animation: {
        "swipe-in-left": "swipe-in-left 0.5s var(--ease_in_out) both",
        "swipe-in-right": "swipe-in-right 0.5s var(--ease_in_out) both",
        "swipe-out-left": "swipe-out-left 0.1s var(--ease_in_out) both",
        "swipe-out-right": "swipe-out-right 0.1s var(--ease_in_out) both",
        "counter--to-top": "counter--to-top .3s var(--ease_out) forwards",
        "counter--to-bottom": "counter--to-bottom .3s var(--ease_out) forwards",
        squize: "squize 0.3s var(--ease_out) forwards",
        "bounce-down": "bounce--down 0.3s var(--ease_out) forwards",
        parallax: "parallax linear",
        "parallax-xl": "parallax-xl linear",
        rotate: "rotate .6s infinite linear",
      },
    },
  },
  plugins: [],
} satisfies Config;
